# General.
base_url = "https://0t1.me"
title = "ZeroToOne"

# Language.
default_language = "en"

# Index content for search.
build_search_index = true

# RSS.
generate_feed = true
feed_filename = "rss.xml"

# Sitemap.xml.
generate_sitemap = true

# Robots.txt.
generate_robots_txt = true

# Performance.
compile_sass = false
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "my-ayu-dark"
extra_syntaxes_and_themes = ["highlight_themes"]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[extra]
# Put all your custom variables here
logo = "#include<0t1>"
author = "Morteza (Mort) NourelahiAlamdari"
